apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        # --- 1. CONTAINER NGINX (Cổng chính - Đón khách) ---
        - name: nginx
          image: "{{ .Values.backend.nginxImage.repository }}:{{ .Values.backend.nginxImage.tag }}"
          imagePullPolicy: Always
          ports:
            # Nginx mở cổng 80 để nhận request từ Service/Ingress
            - containerPort: {{ .Values.backend.containerNginxPort }} 
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 5; nginx -s quit"]

        # --- 2. CONTAINER BACKEND (PHP-FPM - Xử lý ngầm) ---
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always
          ports:
            # QUAN TRỌNG: PHP-FPM chạy port 9000. 
            # Không dùng biến {{ .Values... }} ở đây vì biến đó là 80 (dành cho Nginx).
            - containerPort: {{ .Values.backend.containerPhpPort }}
          env:
            # --- Config Environment ---
            - name: APP_ENV
              value: {{ .Values.backend.env.APP_ENV | quote }}
            - name: APP_DEBUG
              value: {{ .Values.backend.env.APP_DEBUG | quote }}
            - name: APP_URL
              value: "http://{{ .Values.ingress.host }}"
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            
            # --- Secrets (Password/Key) ---
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_USERNAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: JWT_SECRET
